Ext.define('Player.model.ScoSetting', {
    extend: 'Ext.data.Model',
    alias: 'model.scosetting',
    fields: [{
        defaultValue: 0,
        name: 'projectId',
        type: 'int'
    }, {
        name: 'narration',
        type: 'boolean'
    }, {
        name: 'glossary',
        type: 'boolean'
    }, {
        name: 'exitButton',
        type: 'boolean'
    }, {
        name: 'pageNumbering',
        defaultValue: true,
        type: 'boolean'
    }, {
        defaultValue: 'none',
        name: 'tracking',
        type: 'string'
    }, {
        name: 'completion',
        defaultValue: 'completed',
        type: 'string'
    }, {
        name: 'pageComplete',
        defaultValue: true,
        type: 'boolean'
    }, {
        name: 'autoNavigation',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'bookmarking',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'complete',
        type: 'boolean'
    }, {
        name: 'title',
        type: 'string'
    }, {
        name: 'activateTimer',
        type: 'boolean'
    }, {
        name: 'timerSeconds',
        type: 'int'
    }, {
        defaultValue: false,
        name: 'persIndex',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'autoHideToc',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'showHelpOnStart',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'showTocFirst',
        type: 'boolean'
    }, {
        defaultValue: false,
        name: 'useMath',
        type: 'boolean'
    }],
    proxy: {
        type: 'ajax',
        url: 'data/settings.json'
    }
});